##
## 本地规划器base_local_planner的主要作用是根据规划的全局路径，计算发布给机器人的速度指令。
## 该规划器需要我们根据机器人的规格，配置一些相应的参数。
##

controller_frequency: 10.0 # How many times per second should we update the planning process?
                           # A value of 3 to 5 seems to work fairly well for a typical laptop
recovery_behavior_enabled: false
clearing_rotation_allowed: false

TrajectoryPlannerROS:
   #Set the velocity limits of the robot
   max_vel_x: 0.20#0.3
   min_vel_x: 0.1#0.15
   
   max_vel_y: 0.0  # zero for a differential drive robot
   min_vel_y: 0.0
   
   #max_vel_theta: 1.0
   #min_vel_theta: -1.0
   max_vel_theta: 1.57 #pi/6 1/3second
   min_vel_theta: -1.57 #-pi/6
   
   min_in_place_vel_theta: 0.5
   
   escape_vel: -0.1  # speed used for driving during escapes
   
   #Set the acceleration limits of the robot
   acc_lim_x: 2.5
   acc_lim_y: 0.0  # zero for a differential drive robot
   acc_lim_theta: 3.2

   holonomic_robot: false  # 全向
   
   yaw_goal_tolerance: 1.5 #2.5 #0.1 # about 6 degrees How close to the goal orientation (in radians) do we have to get?
   xy_goal_tolerance: 0.15 #0.05  # 5 cm How close (in meters) do we have to get to the goal?
   
   latch_xy_goal_tolerance: false
   pdist_scale: 0.8#0.8#0.4 path_diat
   gdist_scale: 0.2#0.4#0.8 goal_dist
   meter_scoring: true

   heading_lookahead: 0.325
   heading_scoring: false
   heading_scoring_timestep: 0.8
   occdist_scale: 0.05
   oscillation_reset_dist: 0.05
   publish_cost_grid_pc: false
   prune_plan: true

   #We'll configure how long and with what granularity we'll forward simulate trajectories
   sim_time: 1.0
   sim_granularity: 0.05
   angular_sim_granularity: 0.1
   vx_samples: 8
   vy_samples: 0  # zero for a differential drive robot
   vtheta_samples: 20
   dwa: true #false  # Dynamic Window Approach
   simple_attractor: false
   
   
