# From: http://answers.ros.org/question/221899/robot-unable-to-turn-in-place-using-dwa_local_planner/

DWAPlannerROS:
  acc_lim_x: 2.5
  acc_lim_y: 0
  acc_lim_th: 3.0
  max_trans_vel: 0.4
  min_trans_vel: 0.2
  max_vel_x: 0.4
  min_vel_x: 0.2
  max_vel_y: 0
  min_vel_y: 0
  max_rot_vel: 1.2
  min_rot_vel: 0.9

  yaw_goal_tolerance: 0.20
  xy_goal_tolerance: 0.30
  latch_xy_goal_tolerance: false

  sim_time: 1.5
  sim_granularity: 0.025
  vx_samples: 3
  vy_samples: 0
  vtheta_samples: 30
  controller_frequency: 10
  penalize_negative_x: true

  path_distance_bias: 20.0
  goal_distance_bias: 24.0
  occdist_scale: 0.1
  forward_point_distance: 0
  stop_time_buffer: 0.5
  scaling_speed: 0.25
  max_scaling_factor: 0.2

  oscillation_reset_dist: 0.05

  prune_plan: false

  sim_period: 0.1
  rot_stopped_vel: 0.01
  trans_stopped_vel: 0.01
  