##
##	全局规划配置文件用来存储用于全局代价地图的配置参数
##

global_costmap:
   ## global_frame 参数用来表示全局代价地图需要在那个参考系下运行，这里我们选择了map这个参考系。
   ## robot_base_frame参数表示代价地图可以参考的机器人本体的参考系。
   global_frame: /map
   
   robot_base_frame: /base_link
   
   ## update_frequency参数绝地全局地图信息更新的频率，单位是Hz。
   update_frequency: 1.0
   
   publish_frequency: 1.0
   
   ## 如果采用动态地图（实时slam出来的）或者根本不使用先验地图，那可以将全局的costmap所依赖的全局坐标系也改为odom，
   ## rolling_window选项代替static选项，这样costmap就会实时更新，
   ## 要注意的是这样的话你上层程序给出的目标点就不能超过 rolling_window 的范围。 
   
   
   ## static_map参数决定代价地图是否需要根据map_server提供的地图信息进行初始化，
   ## 如果你不需要使用已有的地图或者map_server，最好将该参数设置为false
   static_map: true
   
   rolling_window: false
   
   resolution: 0.05
   
   transform_tolerance: 1.0
   
   map_type: costmap
