#Set the tolerance we're willing to have for tf transforms
#transform_tolerance: 0.3

#Obstacle marking parameters
obstacle_range: 2.5
raytrace_range: 3.0
max_obstacle_height: 0.6
min_obstacle_height: 0.0


#The footprint of the robot and associated padding
#footprint: [[0.45, 0.25], [0.45, -0.25], [-0.45, -0.25], [-0.45, 0.25]]
footprint: [[0.375, 0.30], [0.375, -0.30], [-0.375, -0.30], [-0.375, 0.30]]
inflation_radius: 0.3
#footprint_padding: 0.01
#robot_radius: 0.175

#Configuration for the sensors that the costmap will use to update a map
observation_sources: scan
scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0}

#Cost function parameters
#inflation_radius: 0.55
#cost_scaling_factor: 10.0

#The cost at which a cell is considered an obstacle when a map is read from the map_server
#lethal_cost_threshold: 100
