##
##	全局规划配置文件用来存储用于全局代价地图的配置参数
##

global_costmap:
   ##	global cost map should be run under global_frame, 选择map作为全局代价地图参考系
   ## robot_base_frame 参数表示代价地图可以参考的机器人本体的参考系.
   global_frame: /map
   robot_base_frame: /base_link
   
   ## update_frequency参数决定全局地图信息更新的频率, 单位是Hz
   update_frequency: 1.0
                          # how often the global map is updated with sensor information.
                          # Especially for the global map, a relative small value between 1.0 and 5.0
   publish_frequency: 0 
                          # For a static global map, there is generally no need to continually publish it
   
   
   ## 如果采用动态地图（实时slam出来的）或者根本不使用先验地图, 那可以将全局的costmap所依赖的全局坐标系也改为odom
   ## rolling_window选项代替static选项，这样costmap就会实时更新
   ## 要注意的是这样的话你上层程序给出的目标点就不能超过 rolling_window 的范围.
   ## static_map参数决定代价地图是否需要根据map_server提供的地图信息进行初始化
   ## 如果你不需要使用已有的地图或者map_server，最好将该参数设置为false
   # We'll use a map served by the map_server to initialize this costmap
   static_map: true
                          # The global map is usually static
                          # This parameter and the following one are always set to opposite value.
   rolling_window: false
                          # The global map is generally not updated as the robot moves.
   
   resolution: 0.05
   
   transform_tolerance: 1.0
                          # Specifies the delay in seconds that is tolerated between the frame transforms in the tf tree.
   
   map_type: costmap
   
